### ISSUE TITLE
Error in max-product algorithm

### ISSUE THREAD

**Issue by XintianHan** [danbar/fglib#2]
I just copy your code in max-product algorithm example. But I got 
AttributeError: 'NoneType' object has no attribute 'normalize'.

I guess you do not initialize the value when running the max-product algorithm.

**Comment by danbar** [comment]
Thank you for your feedback.
Please post the full error message, since I cannot reproduce it with the latest master 038dcda.

**Comment by XintianHan** [comment]
Sure.I use the code fglib/examples/example_max. And I got TypeError: object of type 'property' has no len().
![screen shot 2017-12-03 at 4 00 55 pm](https://user-images.githubusercontent.com/31597855/33529772-36bf3f84-d843-11e7-9ee3-fc08768a4240.jpg)

**Comment by danbar** [comment]
I tried a fresh install with 
```
$ pip install fglib
```
and got the following output
```
$ python3 example_max
Maximum of variable node x4:
0.6
Maximum of variable node x3:
0.6
Maximum of variable node x2:
0.586956521739
Unnormalized Maximum of variable node x1:
0.027
```
Could you provide the output of `$ python --version` and `$ pip list`?

**Comment by XintianHan** [comment]
Sure. I tried to uninstall the package and install it again. But it still did not work.
$ python --version
Python 3.6.1 :: Anaconda custom (x86_64)

$ pip list
alabaster (0.7.10)
anaconda-client (1.6.3)
anaconda-navigator (1.6.2)
anaconda-project (0.6.0)
appnope (0.1.0)
appscript (1.0.1)
asn1crypto (0.22.0)
astroid (1.4.9)
astropy (2.0.1)
Babel (2.4.0)
backports.shutil-get-terminal-size (1.0.0)
beautifulsoup4 (4.6.0)
bitarray (0.8.1)
blaze (0.10.1)
bleach (1.5.0)
bokeh (0.12.5)
boto (2.46.1)
Bottleneck (1.2.1)
cffi (1.10.0)
chardet (3.0.3)
click (6.7)
cloudpickle (0.2.2)
clyent (1.2.2)
colorama (0.3.9)
conda (4.3.27)
contextlib2 (0.5.5)
cryptography (1.8.1)
CVXcanon (0.1.1)
cvxopt (1.1.8)
cvxpy (0.4.9)
cycler (0.10.0)
Cython (0.25.2)
cytoolz (0.8.2)
dask (0.14.3)
datashape (0.5.4)
decorator (4.1.2)
dill (0.2.6)
distributed (1.16.3)
docutils (0.13.1)
ecos (2.0.4)
entrypoints (0.2.2)
et-xmlfile (1.0.1)
fastcache (1.0.2)
fglib (0.1)
Flask (0.12.2)
Flask-Cors (3.0.2)
gevent (1.2.1)
greenlet (0.4.12)
h5py (2.7.0)
HeapDict (1.0.0)
html5lib (0.999)
idna (2.5)
imageio (2.1.2)
imagesize (0.7.1)
ipykernel (4.6.1)
ipython (5.3.0)
ipython-genutils (0.2.0)
ipywidgets (6.0.0)
isort (4.2.5)
itsdangerous (0.24)
jdcal (1.3)
jedi (0.10.2)
Jinja2 (2.9.6)
jsonschema (2.6.0)
jupyter (1.0.0)
jupyter-client (5.0.1)
jupyter-console (5.1.0)
jupyter-core (4.3.0)
kenlm (0.0.0)
lazy-object-proxy (1.2.2)
llvmlite (0.19.0)
locket (0.2.0)
lxml (3.7.3)
Markdown (2.6.9)
MarkupSafe (0.23)
matplotlib (2.0.2)
missingno (0.3.7)
mistune (0.7.4)
Mosek (-version-)
moviepy (0.2.3.2)
mpmath (0.19)
msgpack-python (0.4.8)
multipledispatch (0.4.9)
multiprocess (0.70.4)
navigator-updater (0.1.0)
nbconvert (5.1.1)
nbformat (4.3.0)
networkx (2.0)
nltk (3.2.3)
nose (1.3.7)
notebook (5.0.0)
numba (0.34.0)
numexpr (2.6.2)
numpy (1.13.1)
numpydoc (0.6.0)
odo (0.5.0)
olefile (0.44)
openpyxl (2.4.7)
packaging (16.8)
pandas (0.20.3)
pandas-datareader (0.5.0)
pandocfilters (1.4.1)
partd (0.3.8)
pathlib2 (2.2.1)
patsy (0.4.1)
pep8 (1.7.0)
pexpect (4.2.1)
pickleshare (0.7.4)
Pillow (4.1.1)
pip (9.0.1)
plotly (2.0.15)
ply (3.10)
prompt-toolkit (1.0.14)
psutil (5.2.2)
ptyprocess (0.5.1)
py (1.4.33)
pycosat (0.6.2)
pycparser (2.17)
pycrypto (2.6.1)
pycurl (7.43.0)
pyflakes (1.5.0)
Pygments (2.2.0)
pyheatmap (0.1.10)
pyldpc (0.7.6)
pylint (1.6.4)
pynance (0.5.1)
pyodbc (4.0.16)
pyOpenSSL (17.0.0)
pyparsing (2.1.4)
pytest (3.0.7)
python-dateutil (2.6.0)
pytz (2017.2)
PyWavelets (0.5.2)
PyYAML (3.12)
pyzmq (16.0.2)
QtAwesome (0.4.4)
qtconsole (4.3.0)
QtPy (1.2.1)
readme2tex (0.0.1b2)
requests (2.14.2)
requests-file (1.4.2)
requests-ftp (0.3.1)
rope-py3k (0.9.4.post1)
scikit-image (0.13.0)
scikit-learn (0.19.0)
scipy (0.19.1)
scs (1.2.6)
seaborn (0.7.1)
setuptools (27.2.0)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.10.0)
sklearn (0.0)
snowballstemmer (1.2.1)
sortedcollections (0.5.3)
sortedcontainers (1.5.7)
Sphinx (1.5.6)
spyder (3.1.4)
SQLAlchemy (1.1.9)
statsmodels (0.8.0)
sympy (1.0)
tables (3.4.2)
tblib (1.3.2)
terminado (0.6)
testpath (0.3)
toolz (0.8.2)
torch (0.2.0.post4)
torchvision (0.1.9)
tornado (4.5.1)
tqdm (4.11.2)
traitlets (4.3.2)
unicodecsv (0.14.1)
urllib3 (1.22)
wcwidth (0.1.7)
Werkzeug (0.12.2)
wheel (0.29.0)
widgetsnbextension (2.0.0)
wrapt (1.10.10)
xgboost (0.6a2)
xlrd (1.0.0)
XlsxWriter (0.9.6)
xlwings (0.10.4)
xlwt (1.2.0)
zict (0.1.2)

**Comment by XintianHan** [comment]
It works after I upgrade the package. Thanks a lot for your help!
